// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uubcgulimirurnzbzuss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1YmNndWxpbWlydXJuemJ6dXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDIyMzgsImV4cCI6MjA2NDYxODIzOH0.1z3dX1NqOoYweFD820ha9vJBAq67jqfY_OYvPDzg8HM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);